
DROP TABLE GOL;

DROP TABLE JUGAR;

DROP TABLE PARTIDO;

DROP TABLE JUGADOR;

DROP TABLE EQUIPOS;

    CREATE TABLE EQUIPOS
    (EQUIPO VARCHAR2(50) NOT NULL,
    PAIS VARCHAR2(30),
    SELECCIONADOR VARCHAR2(50),
    CONSTRAINT PK_EQUIPOS PRIMARY KEY(EQUIPO));

    
    CREATE TABLE JUGADOR
    (NOMBRE VARCHAR2(60) NOT NULL,
    DIRECCION VARCHAR2(150),
    PUESTO_HAB VARCHAR2(2),
    FECHA_NAC DATE,   
    EQUIPO_JUGADOR VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_JUGADOR PRIMARY KEY(NOMBRE),
    CONSTRAINT JUGADOR_EQUIPO FOREIGN KEY(EQUIPO_JUGADOR) REFERENCES EQUIPOS (EQUIPO));
  
  
    CREATE TABLE PARTIDO
    (EQUIPO_L VARCHAR2(50) NOT NULL,
    EQUIPO_V VARCHAR2(50) NOT NULL,
    FECHA DATE NOT NULL,
    HORA VARCHAR2(8),
    SEDE VARCHAR2(100),
    RESULTADO_L NUMBER,
    RESULTADO_V NUMBER,
    ASISTENCIA NUMBER,
    CONSTRAINT PK_PARTIDO PRIMARY KEY(EQUIPO_L,EQUIPO_V,FECHA),
    CONSTRAINT PARTIDO_EQUIPO_L FOREIGN KEY(EQUIPO_L) REFERENCES EQUIPOS (EQUIPO),
    CONSTRAINT PARTIDO_EQUIPO_V FOREIGN KEY(EQUIPO_V) REFERENCES EQUIPOS (EQUIPO));
  

    CREATE TABLE JUGAR
    (NOMBRE_JUG VARCHAR2(60) NOT NULL,
    EQUIPO_L_PART VARCHAR2(50) NOT NULL,
    EQUIPO_V_PART VARCHAR2(50) NOT NULL,
    FECHA_PART DATE NOT NULL,
    MIN_JUGAR NUMBER(3),
    PUESTO_JUGAR VARCHAR2(2),
    DORSAL NUMBER,    
    CONSTRAINT PK_JUGAR PRIMARY KEY (NOMBRE_JUG,EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART),
    CONSTRAINT JUGAR_JUGADOR FOREIGN KEY(NOMBRE_JUG) REFERENCES JUGADOR (NOMBRE),
    CONSTRAINT JUGAR_EQUIPO FOREIGN KEY(EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART) REFERENCES PARTIDO (EQUIPO_L,EQUIPO_V,FECHA));


    CREATE TABLE GOL
    (MINUTO NUMBER(3) NOT NULL,
    JUGADOR_GOL VARCHAR2(60) NOT NULL, 
    EQUIPO_L_GOL  VARCHAR2(50) NOT NULL,
    EQUIPO_V_GOL VARCHAR2(50) NOT NULL,
    FECHA_GOL DATE NOT NULL,
    CONSTRAINT PK_GOL PRIMARY KEY (MINUTO, JUGADOR_GOL,EQUIPO_L_GOL,EQUIPO_V_GOL,FECHA_GOL),
    CONSTRAINT GOL_JUGAR FOREIGN KEY(JUGADOR_GOL,EQUIPO_L_GOL,EQUIPO_V_GOL,FECHA_GOL) REFERENCES JUGAR (NOMBRE_JUG,EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART));



